name: validate-pubnub-yml

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push]

jobs:
  build:
      name: Validate PubNub yml
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Use Node.js
          uses: actions/setup-node@v1
          with:
            node-version: '12.x'
        - name: Install dependencies
          run: |
            npm install ajv@6.12.6
            npm install yaml@1.10.0
            npm install node-fetch@2.6.1
            npm install chalk@2.4.2
        - name: Validate
          run: GITHUB_TOKEN=${{ secrets.GH_TOKEN }} node ./.github/workflows/validate-yml.js